if(!window.__ELIP_APP_LOADED){window.__ELIP_APP_LOADED=true;
/* Preventivi ELIP — app.js (photo+save fix 2025-10-23)
 * - STOP salvataggio immagini in localStorage (evita QuotaExceededError)
 * - Foto: preview via ObjectURL (no base64)
 * - Salva: registra su Supabase, carica foto, resetta e torna all'Editor
 */
const EURO=n=>(n||0).toLocaleString('it-IT',{style:'currency',currency:'EUR'});
const qs=s=>document.querySelector(s);
window.__elipPhotosQueue = [];
const DEFAULT_CATALOG=[{code:"05",desc:"Smontaggio completo del motore sistematico"},{code:"29",desc:"Lavaggio componenti e trattamento termico avvolgimenti"},{code:"06",desc:"Verifiche meccaniche alberi/alloggi cuscinetti + elettriche avvolgimenti"},{code:"07",desc:"Tornitura, smicatura ed equilibratura rotore"},{code:"22",desc:"Sostituzione collettore con recupero avvolgimento"},{code:"01",desc:"Avvolgimento indotto con recupero collettore"},{code:"01C",desc:"Avvolgimento indotto con sostituzione collettore"},{code:"08",desc:"Isolamento statore"},{code:"02",desc:"Avvolgimento statore"},{code:"31",desc:"Lavorazioni meccaniche albero"},{code:"32",desc:"Lavorazioni meccaniche flange"},{code:"19",desc:"Sostituzione spazzole"},{code:"20",desc:"Sostituzione molle premispazzole"},{code:"21",desc:"Sostituzione cuscinetti"},{code:"23",desc:"Sostituzione tenuta meccanica"},{code:"26",desc:"Sostituzione guarnizioni/paraolio"},{code:"30",desc:"Montaggio, collaudo e verniciatura"},{code:"16",desc:"Ricambi vari"}];
function nextId(){const d=new Date(),y=d.getFullYear(),k='elip_seq_'+y;let s=parseInt(localStorage.getItem(k)||'0',10)+1;localStorage.setItem(k,String(s));return`ELP-${y}-${String(s).padStart(4,'0')}`;}
function getCatalog(){try{return JSON.parse(localStorage.getItem('elip_catalog')||'[]')}catch(_){return[]}}
function setCatalog(a){localStorage.setItem('elip_catalog',JSON.stringify(a));}
function ensureCatalog(){if(getCatalog().length===0)setCatalog(DEFAULT_CATALOG);}
function getCurrent(){try{return JSON.parse(localStorage.getItem('elip_current')||'null')}catch(_){return null}}
function setCurrentLight(o){try{if(!o){localStorage.removeItem('elip_current');return;}const{images,img,photoData,previewData,...rest}=o||{};if(typeof rest.note==='string'&&rest.note.length>4000)rest.note=rest.note.slice(0,4000);localStorage.setItem('elip_current',JSON.stringify(rest));}catch(e){console.warn('[setCurrentLight] skipped:',e?.name||e);try{localStorage.removeItem('elip_current');}catch(_){}}}
function appInitData(){let cur=getCurrent();if(!cur){cur={id:nextId(),createdAt:new Date().toISOString(),cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[]};setCurrentLight(cur);}return cur;}
function clearPage(){const c=appInitData();const b={id:c.id,createdAt:c.createdAt,cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[]};setCurrentLight(b);window.__elipPhotosQueue=[];fillForm();renderLines();renderImages();recalc();}
function buildDatalist(){let dl=document.getElementById('catalogCodes');if(!dl){dl=document.createElement('datalist');dl.id='catalogCodes';document.body.appendChild(dl);}dl.innerHTML='';getCatalog().forEach(x=>{const o=document.createElement('option');o.value=x.code;o.label=`${x.code} - ${x.desc}`;dl.appendChild(o);});}
function renderCatalog(f=''){const ul=qs('#catalogList');if(!ul)return;ul.innerHTML='';const rows=getCatalog().filter(x=>(x.code+x.desc).toLowerCase().includes(f.toLowerCase()));if(rows.length===0){ul.innerHTML='<li class="list-group-item text-muted">Nessuna voce…</li>';return;}rows.forEach(x=>{const li=document.createElement('li');li.className='list-group-item';li.textContent=`${x.code} - ${x.desc}`;li.addEventListener('click',()=>addLine({code:x.code,desc:x.desc,qty:1,price:0,done:false,doneBy:'',doneDate:''}));ul.appendChild(li);});}
function editCatalog(){const t=prompt('Modifica catalogo (JSON):',JSON.stringify(getCatalog(),null,2));if(!t)return;try{const p=JSON.parse(t);if(!Array.isArray(p))throw new Error('Array atteso');setCatalog(p);renderCatalog(qs('#catalogSearch')?.value||'');buildDatalist();}catch(e){alert('JSON non valido: '+e.message);}}
function addLine(r){const c=appInitData();c.lines.push(r);setCurrentLight(c);renderLines();recalc();}
function addCustomLine(){addLine({code:'',desc:'',qty:1,price:0,done:false,doneBy:'',doneDate:''});}
function renderLines(){const c=appInitData(),b=document.getElementById('linesBody');if(!b)return;b.innerHTML='';c.lines.forEach((r,i)=>{const isDone=!!(r.doneDate&&String(r.doneDate).trim().length);r.done=isDone;const tr=document.createElement('tr');if(isDone)tr.classList.add('tr-done');const stateBtn=`<button class="btn-state-dot ${isDone?'green':'red'}" data-state="${i}" title="${isDone?'Completato':'Non eseguito'}"></button>`;tr.innerHTML=`
<td><input class="form-control form-control-sm line-code" list="catalogCodes" data-idx="${i}" value="${r.code||''}" placeholder="Cod."></td>
<td><input class="form-control form-control-sm line-desc" data-idx="${i}" value="${r.desc||''}" placeholder="Descrizione…"></td>
<td><input type="number" min="0" step="1" class="form-control form-control-sm text-end line-qty" data-idx="${i}" value="${r.qty||1}"></td>
<td><input type="number" min="0" step="0.01" class="form-control form-control-sm text-end line-price" data-idx="${i}" value="${r.price||0}"></td>
<td class="text-end" id="lineTot${i}">€ 0,00</td>
<td class="text-center">${stateBtn}</td>
<td><input class="form-control form-control-sm line-operator" data-idx="${i}" value="${r.doneBy||''}" placeholder="Nome operatore"></td>
<td><input type="date" class="form-control form-control-sm line-date" data-idx="${i}" value="${r.doneDate||''}"></td>
<td><button class="btn btn-sm btn-outline-danger" data-del="${i}">✕</button></td>`;b.appendChild(tr);});b.oninput=onLineEdit;b.onclick=onLineClick;}
function onLineEdit(e){const c=appInitData(),id=e.target.dataset.idx;if(e.target.classList.contains('line-code')){const v=e.target.value.trim();c.lines[id].code=v;const hit=getCatalog().find(x=>x.code.toLowerCase()===v.toLowerCase());if(hit){c.lines[id].desc=hit.desc;e.target.closest('tr').querySelector('.line-desc').value=hit.desc;}}if(e.target.classList.contains('line-desc'))c.lines[id].desc=e.target.value;if(e.target.classList.contains('line-qty'))c.lines[id].qty=parseFloat(e.target.value)||0;if(e.target.classList.contains('line-price'))c.lines[id].price=parseFloat(e.target.value)||0;if(e.target.classList.contains('line-operator'))c.lines[id].doneBy=e.target.value;if(e.target.classList.contains('line-date'))c.lines[id].doneDate=e.target.value;setCurrentLight(c);renderLines();recalc();}
function onLineClick(e){const del=e.target.closest('button[data-del]');if(del){const i=+del.getAttribute('data-del');const c=appInitData();c.lines.splice(i,1);setCurrentLight(c);renderLines();recalc();return;}const btn=e.target.closest('button[data-state]');if(btn){const i=+btn.getAttribute('data-state');const row=btn.closest('tr');const dt=row.querySelector('.line-date');if(!dt.value){dt.focus();dt.classList.add('is-invalid');setTimeout(()=>dt.classList.remove('is-invalid'),1200);}else{dt.value='';const c=appInitData();c.lines[i].doneDate='';setCurrentLight(c);renderLines();recalc();}}}
function updateProgressBar(){const c=appInitData();let toDo=0,done=0;c.lines.forEach(r=>{const has=(r.desc||'').trim()!==''||(+r.qty||0)>0||(+r.price||0)>0;if(has){toDo++;if(r.doneDate&&String(r.doneDate).trim().length)done++;}});const pct=toDo?Math.round((done/toDo)*100):0;const bar=document.getElementById('progressBar');if(bar){bar.style.width=pct+'%';bar.textContent=pct+'%';bar.classList.remove('bg-50','bg-100');if(pct>=100)bar.classList.add('bg-100');else if(pct>=50)bar.classList.add('bg-50');}}
function recalc(){const c=appInitData();['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const el=qs('#'+id);if(el)c[id]=el.value;});let imp=0;c.lines.forEach((r,i)=>{const t=(+r.qty||0)*(+r.price||0);imp+=t;const cell=document.getElementById('lineTot'+i);if(cell)cell.textContent=EURO(t);});const iva=imp*0.22,tot=imp+iva;qs('#imponibile').textContent=EURO(imp);qs('#iva').textContent=EURO(iva);qs('#totale').textContent=EURO(tot);const ok=qs('#okPill');const has=(c.dataAcc||'').trim().length>0;ok.classList.toggle('acc-ok',has);ok.classList.toggle('acc-no',!has);ok.textContent=has?'● OK':'● NO';setCurrentLight(c);updateProgressBar();}
function handleImages(files){window.__elipPhotosQueue=Array.from(files||[]);renderImages();}
function renderImages(){const w=qs('#imgPreview');if(!w)return;w.innerHTML='';window.__elipPhotosQueue.forEach((file,i)=>{const url=URL.createObjectURL(file);const d=document.createElement('div');d.className='thumb-wrap';d.innerHTML=`<img class="thumb" src="${url}" data-zoom="${i}"><button class="btn btn-sm btn-outline-danger" data-delimg="${i}">✕</button>`;w.appendChild(d);requestAnimationFrame(()=>URL.revokeObjectURL(url));});w.onclick=e=>{const b=e.target.closest('button[data-delimg]');if(b){const i=+b.getAttribute('data-delimg');window.__elipPhotosQueue.splice(i,1);renderImages();return;}const im=e.target.closest('img[data-zoom]');if(im){const i=+im.getAttribute('data-zoom');const file=window.__elipPhotosQueue[i];if(!file)return;const url=URL.createObjectURL(file);document.getElementById('imgModalImg').src=url;if(window.bootstrap&&bootstrap.Modal)new bootstrap.Modal(document.getElementById('imgModal')).show();setTimeout(()=>URL.revokeObjectURL(url),1500);}};}
function toastSaved(){try{const t=new bootstrap.Toast(document.getElementById('toastSave'),{delay:3000});const now=new Date();document.getElementById('toastSaveMsg').textContent='✅ Preventivo salvato — '+now.toLocaleDateString('it-IT')+' '+now.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});t.show();}catch(_){ }}
function newQuote(){const cur={id:nextId(),createdAt:new Date().toISOString(),cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[]};setCurrentLight(cur);window.__elipPhotosQueue=[];fillForm();renderLines();renderImages();recalc();}
function fillForm(){const c=appInitData();const el=document.getElementById('quoteId');if(el)el.textContent=c.id;['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const x=document.getElementById(id);if(x)x.value=c[id]||'';});const ok=document.getElementById('okPill');if(ok){const has=(c.dataAcc||'').trim().length>0;ok.classList.toggle('acc-ok',has);ok.classList.toggle('acc-no',!has);ok.textContent=has?'● OK':'● NO';}}
function bindAll(){document.getElementById('btnNew')?.addEventListener('click',newQuote);document.getElementById('btnClear')?.addEventListener('click',clearPage);document.getElementById('btnSave')?.addEventListener('click',()=>window.saveToSupabase&&window.saveToSupabase(true));document.getElementById('catalogSearch')?.addEventListener('input',e=>renderCatalog(e.target.value));document.getElementById('btnAddCustom')?.addEventListener('click',()=>addCustomLine());document.getElementById('btnEditCatalog')?.addEventListener('click',()=>editCatalog());['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const el=qs('#'+id);if(el){el.addEventListener('input',recalc);el.addEventListener('change',recalc);}});document.getElementById('imgInput')?.addEventListener('change',e=> e.target.files.length && handleImages(e.target.files));}
function setTabEditorActive(){const btn=document.querySelector('[data-bs-target="#tab-editor"]');if(btn){try{new bootstrap.Tab(btn).show();}catch(_){btn.click();}}}
function init(){ensureCatalog();buildDatalist();renderCatalog();renderLines();fillForm();renderImages();recalc();bindAll();(window.loadArchiveSupabase?window.loadArchiveSupabase():Promise.resolve([])).then(()=>{if(window.subscribeRealtime)window.subscribeRealtime();});}
document.addEventListener('DOMContentLoaded',init);
window.__elipSetCurrentLight=setCurrentLight;
}