if(!window.__ELIP_APP_LOADED){window.__ELIP_APP_LOADED=true;
const EURO=n=>(n||0).toLocaleString('it-IT',{style:'currency',currency:'EUR'});
const qs=s=>document.querySelector(s);
const DEFAULT_CATALOG=[
  {code:"05",desc:"Smontaggio completo del motore sistematico"},
  {code:"29",desc:"Lavaggio componenti e trattamento termico avvolgimenti"},
  {code:"06",desc:"Verifiche meccaniche alberi/alloggi cuscinetti + elettriche avvolgimenti"},
  {code:"07",desc:"Tornitura, smicatura ed equilibratura rotore"},
  {code:"22",desc:"Sostituzione collettore con recupero avvolgimento"},
  {code:"01",desc:"Avvolgimento indotto con recupero collettore"},
  {code:"01C",desc:"Avvolgimento indotto con sostituzione collettore"},
  {code:"08",desc:"Isolamento statore"},
  {code:"02",desc:"Avvolgimento statore"},
  {code:"31",desc:"Lavorazioni meccaniche albero"},
  {code:"32",desc:"Lavorazioni meccaniche flange"},
  {code:"19",desc:"Sostituzione spazzole"},
  {code:"20",desc:"Sostituzione molle premispazzole"},
  {code:"21",desc:"Sostituzione cuscinetti"},
  {code:"23",desc:"Sostituzione tenuta meccanica"},
  {code:"26",desc:"Sostituzione guarnizioni/paraolio"},
  {code:"30",desc:"Montaggio, collaudo e verniciatura"},
  {code:"16",desc:"Ricambi vari"}
];
function nextId(){const d=new Date(),y=d.getFullYear(),k='elip_seq_'+y;let s=parseInt(localStorage.getItem(k)||'0',10)+1;localStorage.setItem(k,String(s));return`ELP-${y}-${String(s).padStart(4,'0')}`;}
function getCatalog(){try{return JSON.parse(localStorage.getItem('elip_catalog')||'[]')}catch(_){return[]}}
function setCatalog(a){localStorage.setItem('elip_catalog',JSON.stringify(a));}
function ensureCatalog(){if(getCatalog().length===0)setCatalog(DEFAULT_CATALOG);}
function getCurrent(){try{return JSON.parse(localStorage.getItem('elip_current')||'null')}catch(_){return null}}
function setCurrent(o){localStorage.setItem('elip_current',JSON.stringify(o));}
function getArchiveLocal(){try{return JSON.parse(localStorage.getItem('elip_archive')||'[]')}catch(_){return[]}}
function appInitData(){let cur=getCurrent();if(!cur){cur={id:nextId(),createdAt:new Date().toISOString(),cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[],images:[]};setCurrent(cur);}return cur;}
function clearPage(){const c=appInitData();const b={id:c.id,createdAt:c.createdAt,cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[],images:[]};setCurrent(b);fillForm();renderLines();renderImages();recalc();}
function buildDatalist(){let dl=document.getElementById('catalogCodes');if(!dl){dl=document.createElement('datalist');dl.id='catalogCodes';document.body.appendChild(dl);}dl.innerHTML='';getCatalog().forEach(x=>{const o=document.createElement('option');o.value=x.code;o.label=`${x.code} - ${x.desc}`;dl.appendChild(o);});}
function renderCatalog(f=''){const ul=qs('#catalogList');if(!ul)return;ul.innerHTML='';const rows=getCatalog().filter(x=>(x.code+x.desc).toLowerCase().includes(f.toLowerCase()));if(rows.length===0){ul.innerHTML='<li class="list-group-item text-muted">Nessuna voce…</li>';return;}rows.forEach(x=>{const li=document.createElement('li');li.className='list-group-item';li.textContent=`${x.code} - ${x.desc}`;li.addEventListener('click',()=>addLine({code:x.code,desc:x.desc,qty:1,price:0,done:false,doneBy:'',doneDate:''}));ul.appendChild(li);});}
function editCatalog(){const t=prompt('Modifica catalogo (JSON):',JSON.stringify(getCatalog(),null,2));if(!t)return;try{const p=JSON.parse(t);if(!Array.isArray(p))throw new Error('Array atteso');setCatalog(p);renderCatalog(qs('#catalogSearch')?.value||'');buildDatalist();}catch(e){alert('JSON non valido: '+e.message);}}
function addLine(r){const c=appInitData();c.lines.push(r);setCurrent(c);renderLines();recalc();}
function addCustomLine(){addLine({code:'',desc:'',qty:1,price:0,done:false,doneBy:'',doneDate:''});}
function renderLines(){const c=appInitData(),b=document.getElementById('linesBody');if(!b)return;b.innerHTML='';c.lines.forEach((r,i)=>{const isDone=!!(r.doneDate&&String(r.doneDate).trim().length);r.done=isDone;const tr=document.createElement('tr');if(isDone)tr.classList.add('tr-done');const stateBtn=`<button class="btn-state-dot ${isDone?'green':'red'}" data-state="${i}" title="${isDone?'Completato':'Non eseguito'}"></button>`;tr.innerHTML=`
<td><input class="form-control form-control-sm line-code" list="catalogCodes" data-idx="${i}" value="${r.code||''}" placeholder="Cod."></td>
<td><input class="form-control form-control-sm line-desc" data-idx="${i}" value="${r.desc||''}" placeholder="Descrizione…"></td>
<td><input type="number" min="0" step="1" class="form-control form-control-sm text-end line-qty" data-idx="${i}" value="${r.qty||1}"></td>
<td><input type="number" min="0" step="0.01" class="form-control form-control-sm text-end line-price" data-idx="${i}" value="${r.price||0}"></td>
<td class="text-end" id="lineTot${i}">€ 0,00</td>
<td class="text-center">${stateBtn}</td>
<td><input class="form-control form-control-sm line-operator" data-idx="${i}" value="${r.doneBy||''}" placeholder="Nome operatore"></td>
<td><input type="date" class="form-control form-control-sm line-date" data-idx="${i}" value="${r.doneDate||''}"></td>
<td><button class="btn btn-sm btn-outline-danger" data-del="${i}">✕</button></td>`;b.appendChild(tr);});b.oninput=onLineEdit;b.onclick=onLineClick;}
function onLineEdit(e){const c=appInitData(),id=e.target.dataset.idx;if(e.target.classList.contains('line-code')){const v=e.target.value.trim();c.lines[id].code=v;const hit=getCatalog().find(x=>x.code.toLowerCase()===v.toLowerCase());if(hit){c.lines[id].desc=hit.desc;e.target.closest('tr').querySelector('.line-desc').value=hit.desc;}}if(e.target.classList.contains('line-desc'))c.lines[id].desc=e.target.value;if(e.target.classList.contains('line-qty'))c.lines[id].qty=parseFloat(e.target.value)||0;if(e.target.classList.contains('line-price'))c.lines[id].price=parseFloat(e.target.value)||0;if(e.target.classList.contains('line-operator'))c.lines[id].doneBy=e.target.value;if(e.target.classList.contains('line-date'))c.lines[id].doneDate=e.target.value;setCurrent(c);renderLines();recalc();}
function onLineClick(e){const del=e.target.closest('button[data-del]');if(del){const i=+del.getAttribute('data-del');const c=appInitData();c.lines.splice(i,1);setCurrent(c);renderLines();recalc();return;}const btn=e.target.closest('button[data-state]');if(btn){const i=+btn.getAttribute('data-state');const row=btn.closest('tr');const dt=row.querySelector('.line-date');if(!dt.value){dt.focus();dt.classList.add('is-invalid');setTimeout(()=>dt.classList.remove('is-invalid'),1200);}else{dt.value='';const c=appInitData();c.lines[i].doneDate='';setCurrent(c);renderLines();recalc();}}}
function updateProgressBar(){const c=appInitData();let toDo=0,done=0;c.lines.forEach(r=>{const has=(r.desc||'').trim()!==''||(+r.qty||0)>0||(+r.price||0)>0;if(has){toDo++;if(r.doneDate&&String(r.doneDate).trim().length)done++;}});const pct=toDo?Math.round((done/toDo)*100):0;const bar=document.getElementById('progressBar');if(bar){bar.style.width=pct+'%';bar.textContent=pct+'%';bar.classList.remove('bg-50','bg-100');if(pct>=100)bar.classList.add('bg-100');else if(pct>=50)bar.classList.add('bg-50');}}
function recalc(){const c=appInitData();['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const el=qs('#'+id);if(el)c[id]=el.value;});let imp=0;c.lines.forEach((r,i)=>{const t=(+r.qty||0)*(+r.price||0);imp+=t;const cell=document.getElementById('lineTot'+i);if(cell)cell.textContent=EURO(t);});const iva=imp*0.22,tot=imp+iva;qs('#imponibile').textContent=EURO(imp);qs('#iva').textContent=EURO(iva);qs('#totale').textContent=EURO(tot);const ok=qs('#okPill');const has=(c.dataAcc||'').trim().length>0;ok.classList.toggle('acc-ok',has);ok.classList.toggle('acc-no',!has);ok.textContent=has?'● OK':'● NO';setCurrent(c);updateProgressBar();}
function handleImages(files){const c=appInitData();const p=[...files].map(f=>new Promise(res=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.readAsDataURL(f);}));Promise.all(p).then(a=>{c.images=(c.images||[]).concat(a);setCurrent(c);renderImages();});}
function renderImages(){const c=appInitData(),w=qs('#imgPreview');if(!w)return;w.innerHTML='';(c.images||[]).forEach((src,i)=>{const d=document.createElement('div');d.className='thumb-wrap';d.innerHTML=`<img class="thumb" src="${src}" data-zoom="${i}"><button class="btn btn-sm btn-outline-danger" data-delimg="${i}">✕</button>`;w.appendChild(d);});w.onclick=e=>{const b=e.target.closest('button[data-delimg]');if(b){const i=+b.getAttribute('data-delimg');const c=appInitData();c.images.splice(i,1);setCurrent(c);renderImages();return;}const im=e.target.closest('img[data-zoom]');if(im){const i=+im.getAttribute('data-zoom');const c=appInitData();document.getElementById('imgModalImg').src=c.images[i];if(window.bootstrap&&bootstrap.Modal)new bootstrap.Modal(document.getElementById('imgModal')).show();}};}
async function headerPDF(doc,pad,cur){try{const img=await fetch('logo-elip.jpg?v=2').then(r=>r.blob()).then(b=>new Promise(res=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.readAsDataURL(b);}));doc.addImage(img,'JPEG',pad,40,160,40);}catch(_){ }doc.setFontSize(18);doc.text('Preventivo',pad,110);doc.setFontSize(12);const dIT=new Date().toLocaleDateString('it-IT');doc.text(`Data: ${dIT}  •  N°: ${cur.id}`,pad,128);doc.setFontSize(12.5);doc.text('Cliente: '+(cur.cliente||'-'),pad,148);doc.text('Articolo: '+(cur.articolo||'-'),pad,166);doc.text('DDT: '+(cur.ddt||'-'),pad,184);doc.text(`Telefono: ${cur.telefono||'-'}   Email: ${cur.email||'-'}`,pad,202);}
function totalsPDF(doc,pad,cur,startY){const imp=(cur.lines||[]).reduce((s,r)=>s+(+r.qty||0)*(+r.price||0),0);const iva=imp*0.22,tot=imp+iva;let y=startY;doc.setFontSize(13);doc.text('Riepilogo',pad,y);y+=12;doc.setFontSize(12);doc.text('Imponibile: '+EURO(imp),pad,y);y+=14;doc.text('IVA (22%): '+EURO(iva),pad,y);y+=16;doc.setFontSize(14);doc.text('TOTALE: '+EURO(tot),pad,y);return y+20;}
async function buildPDF(type){const {jsPDF}=window.jspdf||{};if(!jsPDF){alert('PDF non disponibile');return;}const cur=appInitData(),doc=new jsPDF({unit:'pt',format:'a4'}),pad=40;await headerPDF(doc,pad,cur);const pageW=doc.internal.pageSize.getWidth();const avail=pageW-pad*2;if(type==='dett'){const colW={cod:55,qty:55,price:80,tot:90};colW.desc=Math.max(160,avail-(colW.cod+colW.qty+colW.price+colW.tot));const rows=(cur.lines||[]).length?cur.lines.map(r=>[r.code||'',r.desc||'',String(r.qty||0),EURO(r.price||0),EURO((+r.qty||0)*(+r.price||0))]):[['','','0','€ 0,00','€ 0,00']];doc.autoTable({startY:230,head:[['Cod','Descrizione','Q.tà','Prezzo','Totale']],body:rows,margin:{left:pad,right:pad},tableWidth:avail,styles:{fontSize:10.5,cellPadding:6,overflow:'linebreak',valign:'top'},headStyles:{fillColor:[199,119,59]},columnStyles:{0:{cellWidth:colW.cod},1:{cellWidth:colW.desc},2:{cellWidth:colW.qty,halign:'right'},3:{cellWidth:colW.price,halign:'right'},4:{cellWidth:colW.tot,halign:'right'}}});}else{const colCod=60,colDesc=Math.max(200,avail-colCod);const rows=(cur.lines||[]).length?cur.lines.map(r=>[r.code||'',r.desc||'']):[['','Nessuna voce']];doc.autoTable({startY:230,head:[['Cod','Descrizione incluse']],body:rows,margin:{left:pad,right:pad},tableWidth:avail,styles:{fontSize:11,cellPadding:7,overflow:'linebreak',valign:'top'},headStyles:{fillColor:[199,119,59]},columnStyles:{0:{cellWidth:colCod},1:{cellWidth:colDesc}}});}let y=doc.lastAutoTable.finalY+14;const note=(appInitData().note||'').trim();if(note){doc.setFontSize(13);doc.text('NOTE',pad,y);y+=10;doc.setFontSize(11.5);const tx=doc.splitTextToSize(note,avail);doc.text(tx,pad,y);y+=tx.length*14+8;}totalsPDF(doc,pad,cur,y+6);for(const src of (cur.images||[])){const im=new Image();im.src=src;await im.decode();const r=Math.min(avail/im.width,500/im.height);const w=Math.round(im.width*r),h=Math.round(im.height*r);doc.addPage();doc.setFontSize(12);doc.text('Immagine allegata',pad,80);doc.addImage(src,'JPEG',pad,100,w,h);}return doc;}
async function previewPDF(type){const doc=await buildPDF(type);if(!doc)return;const blob=doc.output('blob');const url=URL.createObjectURL(blob);const f=document.getElementById('pdfFrame');f.src=url;const a=document.getElementById('btnDownload');a.href=url;a.download=(appInitData().id)+'-'+(type==='dett'?'dettaglio':'totale')+'.pdf';if(window.bootstrap&&bootstrap.Modal)new bootstrap.Modal(document.getElementById('pdfModal')).show();else window.open(url,'_blank');}
function jpgCover(){const c=appInitData();const cv=document.createElement('canvas');cv.width=1200;cv.height=900;const g=cv.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,cv.width,cv.height);g.fillStyle='#c7773b';g.fillRect(0,0,cv.width,120);g.fillStyle='#fff';g.font='bold 52px Arial';g.fillText('ELIP TAGLIENTE — Preventivo',40,80);g.fillStyle='#333';g.font='28px Arial';g.fillText('N°: '+c.id,40,160);g.fillText('Cliente: '+(c.cliente||'-'),40,200);g.fillText('Articolo: '+(c.articolo||'-'),40,240);g.fillText('DDT: '+(c.ddt||'-'),40,280);const imp=(c.lines||[]).reduce((s,r)=>s+(+r.qty||0)*(+r.price||0),0);const iva=imp*0.22;const tot=imp+iva;g.fillText('Totale (IVA 22%): '+EURO(tot),40,320);g.font='bold 24px Arial';g.fillText('Voci incluse',40,370);g.font='20px Arial';let y=410;c.lines.slice(0,12).forEach(r=>{g.fillText(`${r.code||''} — ${r.desc||''}`,40,y);y+=28;});const url=cv.toDataURL('image/jpeg',0.92);const l=document.getElementById('btnJPG');l.href=url;l.download=c.id+'-anteprima.jpg';}
function shareMail(){const c=appInitData();const imp=(c.lines||[]).reduce((s,r)=>s+(+r.qty||0)*(+r.price||0),0);const tot=imp*1.22;const subject=encodeURIComponent(`ELIP Tagliente — Preventivo ${c.id}`);const lines=(c.lines||[]).map(r=>`• ${r.code||''} - ${r.desc||''}`).join('\\n');const body=`Spett.le CLIENTE

Alleghiamo alla presente il documento in oggetto

Di seguito il riepilogo dei lavori preventivati:
${lines}

Totale complessivo (IVA 22%): ${EURO(tot)}

Con l'occasione, 

porgiamo distinti saluti.


ELIP Tagliente Srl
VIA CONCHIA, 54/E  70043 MONOPOLI (BA)
P.IVA/C.F.: 04386020723
TEL. 080.777090  FAX 080.8876756
MAIL: info@eliptagliente.it  WEB. www.eliptagliente.it
POSTA CERTIFICATA: eliptagliente@pec.it
Codice SDI          M5UXCR1
BANCA POPOLARE DI BARI (FIL. MONOPOLI – BA)
IBAN IT02U0542441570000001006392
BIC/SWIFT CODE: BPBAIT3B`;window.location.href='mailto:'+(c.email||'')+'?subject='+subject+'&body='+encodeURIComponent(body);}
function shareWA(){const c=appInitData();const lines=(c.lines||[]).map(r=>`• ${r.code||''} ${r.desc||''}`).join('%0A');const msg=encodeURIComponent(`ELIP Tagliente — Preventivo ${c.id}%0ACliente: ${c.cliente||'-'}%0ATotale: ${qs('#totale').textContent}%0A%0AVoci:%0A`)+lines;window.open('https://wa.me/?text='+msg,'_blank');}
window.ACC_FILTER='all';
function computeAccCounters(a){let ok=0,no=0;a.forEach(r=>((r.data_accettazione||'').toString().trim()?ok++:no++));const el=document.getElementById('accCounters');if(el)el.textContent=`Accettati: ${ok} — Da accettare: ${no}`;}
function renderArchiveLocal(){const arr=getArchiveLocal();computeAccCounters(arr);const q=(document.getElementById('filterQuery')?.value||'').toLowerCase();const body=document.getElementById('archBody');if(!body)return;body.innerHTML='';const today=new Date();today.setHours(0,0,0,0);arr.filter(r=>(r.cliente||'').toLowerCase().includes(q)).filter(r=>(window.ACC_FILTER==='all')||(window.ACC_FILTER==='ok'&&(r.data_accettazione||'').toString().trim())||(window.ACC_FILTER==='no'&&!(r.data_accettazione||'').toString().trim())).forEach(rec=>{const tot=(rec.totale!=null)?rec.totale:((rec.linee||[]).reduce((s,r)=>s+(+r.qty||0)*(+r.price||0),0)*1.22);const toDo=(rec.linee||[]).filter(r=>(r.desc||'').trim()!==''||(+r.qty||0)>0||(+r.price||0)>0).length;const done=(rec.linee||[]).filter(r=>r.doneDate&&String(r.doneDate).trim().length).length;const pct=toDo?Math.round((done/toDo)*100):0;const dot=pct===100?'<span class="progress-dot" style="color:var(--green)">●</span>':(pct>=50?'<span class="progress-dot" style="color:var(--warn)">●</span>':'<span class="progress-dot" style="color:var(--red)">●</span>');let scad='<span class="text-muted">-</span>';if(rec.data_scadenza){const d=new Date(rec.data_scadenza);d.setHours(0,0,0,0);const diff=Math.round((d-today)/(1000*60*60*24));if(diff<=5&&diff>=0)scad=`<span class="badge badge-deadline">Scade in ${diff} g</span>`;else if(diff<0)scad='<span class="badge bg-danger">Scaduto</span>';else scad=new Date(rec.data_scadenza).toLocaleDateString('it-IT');}const acc=(rec.data_accettazione||'').toString().trim()?'<span class="acc-pill acc-ok">● OK</span>':'<span class="acc-pill acc-no">● NO</span>';const itDate=new Date(rec.created_at||rec.createdAt||Date.now()).toLocaleDateString('it-IT');const tr=document.createElement('tr');tr.innerHTML=`<td>${rec.numero||rec.id}</td><td>${itDate}</td><td>${rec.cliente||''}</td><td>${rec.articolo||''}</td><td>${rec.ddt||''}</td><td>${EURO(tot||0)}</td><td>${acc}</td><td>${scad}</td><td>${dot} ${pct}%</td><td><button class="btn btn-sm btn-outline-primary" data-open="${rec.id}">Modifica</button></td>`;body.appendChild(tr);});body.onclick=e=>{const b=e.target.closest('button[data-open]');if(!b)return;const id=b.getAttribute('data-open');const rec=getArchiveLocal().find(x=>x.id===id);if(!rec)return;const cur={id:rec.numero||rec.id,createdAt:rec.created_at,cliente:rec.cliente,articolo:rec.articolo,ddt:rec.ddt,telefono:rec.telefono,email:rec.email,dataInvio:rec.data_invio,dataAcc:rec.data_accettazione,dataScad:rec.data_scadenza,note:rec.note,lines:rec.linee||[],images:rec.images||[]};setCurrent(cur);document.querySelector('[data-bs-target="#tab-editor"]').click();renderLines();fillForm();renderImages();recalc();};}
function toastSaved(){const t=new bootstrap.Toast(document.getElementById('toastSave'),{delay:3000});const now=new Date();document.getElementById('toastSaveMsg').textContent='✅ Preventivo salvato — '+now.toLocaleDateString('it-IT')+' '+now.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});t.show();}
function newQuote(){const cur={id:nextId(),createdAt:new Date().toISOString(),cliente:'',articolo:'',ddt:'',telefono:'',email:'',dataInvio:'',dataAcc:'',dataScad:'',note:'',lines:[],images:[]};setCurrent(cur);fillForm();renderLines();renderImages();recalc();}
function setFilterButtons(){}
function fillForm(){const c=appInitData();const el=document.getElementById('quoteId');if(el)el.textContent=c.id;['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const x=document.getElementById(id);if(x)x.value=c[id]||'';});const ok=document.getElementById('okPill');const has=(c.dataAcc||'').trim().length>0;ok.classList.toggle('acc-ok',has);ok.classList.toggle('acc-no',!has);ok.textContent=has?'● OK':'● NO';}
function bindAll(){document.getElementById('btnNew')?.addEventListener('click',newQuote);document.getElementById('btnClear')?.addEventListener('click',clearPage);document.getElementById('btnSave')?.addEventListener('click',()=>window.saveToSupabase&&window.saveToSupabase(true));document.getElementById('btnPDFDett')?.addEventListener('click',()=>previewPDF('dett'));document.getElementById('btnPDFTot')?.addEventListener('click',()=>previewPDF('tot'));document.getElementById('btnJPG')?.addEventListener('click',jpgCover);document.getElementById('btnMail')?.addEventListener('click',shareMail);document.getElementById('btnWA')?.addEventListener('click',shareWA);document.getElementById('catalogSearch')?.addEventListener('input',e=>renderCatalog(e.target.value));document.getElementById('btnAddCustom')?.addEventListener('click',addCustomLine);document.getElementById('btnEditCatalog')?.addEventListener('click',editCatalog);['cliente','articolo','ddt','telefono','email','dataInvio','dataAcc','dataScad','note'].forEach(id=>{const el=qs('#'+id);if(el){el.addEventListener('input',recalc);el.addEventListener('change',recalc);}});document.getElementById('imgInput')?.addEventListener('change',e=>e.target.files.length&&handleImages(e.target.files));document.getElementById('btnReloadArch')?.addEventListener('click',()=>window.loadArchiveSupabase?window.loadArchiveSupabase().then(renderArchiveLocal):renderArchiveLocal());document.getElementById('filterQuery')?.addEventListener('input',renderArchiveLocal);document.getElementById('fltAll')?.addEventListener('click',()=>{window.ACC_FILTER='all';renderArchiveLocal();});document.getElementById('fltOk')?.addEventListener('click',()=>{window.ACC_FILTER='ok';renderArchiveLocal();});document.getElementById('fltNo')?.addEventListener('click',()=>{window.ACC_FILTER='no';renderArchiveLocal();});}
function init(){ensureCatalog();buildDatalist();renderCatalog();renderLines();fillForm();renderImages();recalc();bindAll();(window.loadArchiveSupabase?window.loadArchiveSupabase():Promise.resolve([])).then(()=>{renderArchiveLocal();if(window.subscribeRealtime)window.subscribeRealtime();});}
document.addEventListener('DOMContentLoaded',init);
}
